#index:
#    path: /
#    controller: App\Controller\DefaultController::index

books_list:
  path: /books
  controller: App\Controller\ApiController::bookList
  methods: [GET]

books_add:
  path: /books
  controller: App\Controller\ApiController::bookCreate
  methods: [POST]

categories_list:
  path: /categories
  controller: App\Controller\ApiController::categoryList
  methods: [GET]
