#index:
#    path: /
#    controller: App\Controller\DefaultController::index

books:
  path: /books
  controller: App\Controller\ApiController::books

categories:
  path: /categories
  controller: App\Controller\ApiController::categories